Repository K-Hacks/HacktoberFest-2022, pull requests merged in 2022-10, with the labels that each got.

#1 Test PR
  index.html
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#43 Add files via upload
  Python_Basic_Concepts.ipynb
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#42 Create form.html
  form.html
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#41 "hashing"
  hashing.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#40 Commit_2
  Merge_Sort.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#38 Create hi.py
  hi.py
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#37 Create FEBY
  FEBY
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#36 First pull request (°-°).
  NumberAnalysis.c
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#34 Committing rohan.html
  rohan.html
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#33 Create samuel
  samuel
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#32 Create bharath.html
  bharath.html
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#31 Create hi html
  hi html
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#30 Create ragul.py
  ragul.py
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#29 Create thesecond.txt
  thesecond.txt
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#28 Create jefarin.py
  jefarin.py
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#27 Create Berry Samuel.txt
  Berry Samuel.txt
Labels: hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#20 Create srgabriel.text
  srgabriel.text
Labels: hacktoberfest

#14 Create Akash
  Akash
Labels: hacktoberfest

#2 Create shannan
  shannan
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#3 Create yamborghini
  yamborghini
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#9 Create anand
  anand
Labels: hacktoberfest

#13 Create bestwin
  bestwin
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#4 Create riyaz
  riyaz
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#8 Create steeve
  steeve
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#5 Create Chris
  Chris
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#6 Create indeX
  indeX
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#7 Create GRAESON
  GRAESON
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#26 Create Hello World.txt
  Hello World.txt
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#25 Create jen.txt
  jen.txt
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#24 Create whatever.txt
  okay.txt
  whatever.txt
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#10 Create demo
  demo
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#23 Create hai.html
  hai.html
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#16 first user commit
  README.md
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#18 Create github
  github
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#15 tamil.py
  tamil.hacks
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#11 Create EVALT
  EVALT
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#12 Create mohan
  mohan
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#21 Create Anto_Godwin.txt
  Anto_Godwin.txt
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#19 bk
  bharath-code
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#22 Create hai
  hai
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#69 FourtH!
  calci.java
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#71 Add Battleships
  5x5 Battleship game.py
  Game_of_Life/Game_GUI.py
  Game_of_Life/Game_of_Life.py
  Game_of_Life/description.txt
  Trees
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#72 Create Alarm_clock.py
  Alarm_clock.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#73 Create Quicksort
  Quicksort
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#75 Created IP-Addresses
  IP-addresses
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#77 Create seven.py
  seven.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#78 Create LinkedList.py
  LinkedList.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#96 New branch4
  Atm-Machine/bank.py
  Atm-Machine/main.py
  Credit Card Fraud Detection.ipynb
  GUI calculator.py
  Image to Pencil Sketch with Python.ipynb
  quizgame.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#93 added starTurtle.py
  starTurtle.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#92 added pattern.py
  pattern.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#91 added text.txt file
  taxt.txt
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#89 added star.c
  star.c
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#45 Create Merge_Sorting.py
  Merge_Sorting.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#46 Commit 1 for hacktober 2022
  one.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#48 Create threadMerging.java
  threadMerging.java
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#49 Create THREE.py
  THREE.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#63 Create third.py
  third.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#65 Create fourth.py
  fourth.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#66 Create qrcode.py
  qrcode.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#67 Create fifth.py
  fifth.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#68 Create Dice_sim.py
  Dice_sim.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#79 Create Shutdownyourpc.py
  Shutdownyourpc.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#80 Create spiral.py
  spiral.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#82 Create 01.py
  01.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#83 Create 02.py
  02.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#84 Create 03.py
  03.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#85 Create 04.py
  04.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#86 added zigzag.py
  zigzag.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#87 Create 05.py
  05.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr

#88 Create 06.py
  06.py
Labels: hacktoberfest, hacktoberfest-2022, hacktoberfest-accepted, good-first-pr
